# Generated by Django 3.2.7 on 2021-09-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('therapist', 'Терапевт'), ('sergeon', 'хирург')], default='therapist', max_length=255, verbose_name='Терапевт/Хирург')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО ')),
                ('pin', models.CharField(max_length=4, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Лечащий врач',
                'verbose_name_plural': 'Лечащие врачи',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.CharField(choices=[('Osh', 'Ошская'), ('Chui', 'Чуйская'), ('IK', 'Иссык-Кульская'), ('Talas', 'Таласская'), ('Naryn', 'Нарынская'), ('DjA', 'Джалал-Абадская'), ('Batken', 'Баткенская')], default='Osh', max_length=9, verbose_name='Область')),
                ('ocpo', models.CharField(max_length=4, unique=True, verbose_name='ОКПО')),
                ('gov', models.BooleanField(default=False, verbose_name='Государственное')),
                ('maxn', models.IntegerField(default=100, verbose_name='Макс.количество сотрудников')),
            ],
            options={
                'verbose_name': 'Больница',
                'verbose_name_plural': 'Больницы',
            },
        ),
        migrations.CreateModel(
            name='MainDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('pin', models.CharField(max_length=14, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'ГлавВрач',
                'verbose_name_plural': 'ГлавВрачи',
            },
        ),
        migrations.CreateModel(
            name='Nurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО ')),
                ('pin', models.CharField(max_length=4, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Медсестра',
                'verbose_name_plural': 'Медсестры',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО ')),
                ('pin', models.CharField(max_length=4, verbose_name='ПИН')),
                ('birthdate', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('reason', models.CharField(max_length=255, verbose_name='Причина обращения в больницу')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='main.doctor', verbose_name='Лечащий врач')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.hospital', verbose_name='Больница')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nurses', verbose_name='Медсестра')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.maindoctor', verbose_name='ГлавВрач'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.hospital', verbose_name='Больница'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nurses', verbose_name='Медсестра'),
        ),
    ]
